- README.md
- lib/index.js
http://node-webkit.org has been moved to http://nwjs.io
Note that this will fix all downloads except for 0.12.0-alpha1 due to the name change.
> fixed downloads after move to nwjs.io

- lib/utils.js
- test/expected/osx-plist/2.plist
Fun fact: trying to google for issues with "osx about screen" will just give you info *about* osx screens. :disappointed:
Anyway...
If you dont set a copyright, then the "My App" -> "About My App" window in osx will not open on the first click, and on the second click will give you this:
Note the weird version string even if the version number is set.
If you supply the copyright info, then everything works and you get this:
Which is all hunky dory.
The problem is caused by `NSHumanReadableCopyright` being set to `false` in the Info.plist if the copyright info isnt supplied to node-webkit-builder. This causes osx to cry as it expects a string. From the [spec](https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html):
> …
> fixed broken osx about screen when copyright not supplied

- lib/utils.js
When file doesn't exist after copy, DO NOT COPY IT AGAIN. We will only check its existence again.
fixes #147
> Fix copyFile method

- example/package.json
build fail in example.  error message is "Error: unknown platform win32".
This error is caused by older version of node-webkit-builder.
so fixed package.json.
> fixed build fail in example. downloading nwbuild version is old.

- lib/index.js
Sometimes you need access to the reference of the child process created when launching nw using run(). This commit attempts to expose it in an orderly manner
> Safely access child process reference created when using run()

- lib/utils.js
I had macPlist overrides set to:
```json
{
"CFBundleDocumentTypes": [{
"CFBundleTypeExtensions": ["html","htm"],
"CFBundleTypeIconFile": "nw.icns",
"CFBundleTypeMIMETypes": ["text/html"],
"CFBundleTypeName": "HTML dokument",
"CFBundleTypeOSTypes": ["HTML"],
"CFBundleTypeRole":"Viewer"
},{
"CFBundleTypeExtensions":["xhtml"],
"CFBundleTypeIconFile":"nw.icns",
"CFBundleTypeMIMETypes":["text/xhtml"],
"CFBundleTypeName":"XHTML dokument",
"CFBundleTypeRole":"Viewer"
}]
}
```
but in the Info.plist was:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleDocumentTypes</key>
<array />
</dict>
</plist>
```
now it is correctly:
```xml
<?xml version="1.0" …
```
> Fix for overwriting specified mac plist properties

- lib/index.js
I'm getting this error message as per issue #227. I don't know how to fix it at this time but I thought perhaps the URL hadn't been updated from node-webkit.org to nwjs.io. Looking at the code, the URL is correct; only the error message is incorrect so I figured I'd update the error to eliminate some confusion.
> Modified the error message when it fails to download a build.

- lib/index.js
Right now it's impossible to know when the NW.js process is starting after calling `run()`. The promise will be resolved when killing the application, so the promise itself can't be used for getting the NW.js process.
With this change an `appstart` event will be triggered right after spawning the NW.js process. There's also an error callback added, which will reject the promise in case of an error.
> runApp "appstart" event

- lib/platforms.js
This avoids this version matching if evaluated before the next rule
(>=0.12.0) which would end up not including files like pdf.dll
> put upper bound to semver check for windows

- README.md
- lib/index.js
- lib/platforms.js
As large projects might result in slow application startup times, I suggest the following changes to introduce a winZip option. This option defaults to true (which leaves node-webkit-builder's behavior unchanged) and can be set to false to allow putting the application uncompressed next to the executable.
See:
https://github.com/mllrsohn/node-webkit-builder/issues/195
> added option for winZip similar to macZip

- .gitignore
- .travis.yml
- appveyor.yml
- example/Gulpfile.js
- lib/Version.js
- lib/downloader.js
- lib/index.js
- lib/utils.js
- lib/versions.js
- package.json
- test/fixtures/manifest/versions.json
- test/fixtures/testVersions.html
- test/nwBuilder.js
- test/versions.js
For #329.
I have only tested this on Mac OS X as I'm abroad right now and I only have my laptop. I'd appreciate it if someone could run our tests and do some manual tests on an example app with varying config.
~~On Mac OS X, there's a problem when building a Mac app with a newer version (e.g. 0.15.2) in that the app name displayed in Finder is `nwjs.app`. I'm not sure why. I've created a StackOverflow question; [App name in Finder not matching app name in Terminal](http://stackoverflow.com/questions/37890440/app-name-in-finder-not-matching-app-name-in-terminal).~~
> Supporting newer NW.js versions

- .gitignore
- .travis.yml
- README.md
- appveyor.yml
- example/Gulpfile.js
- lib/Version.js
- lib/downloader.js
- lib/index.js
- lib/utils.js
- lib/versions.js
- package.json
- test/fixtures/manifest/versions.json
- test/fixtures/testVersions.html
- test/nwBuilder.js
- test/versions.js
Newer versions now work, plus other fixes.
Resolves #321, #327, #233, #216, #206.
> 2.2.1 - Phoenix

- lib/versions.js
Fixes #343 
This also fixes an issue when defining non-existing versions. Using `0.1000.0` for instance doesn't return a proper error message right now, but instead fails with a "Cannot read property 'linux64' of undefined" error. I'm not sure why [the non-existing versions test](https://github.com/nwjs/nw-builder/blob/0d43c4dfdded6a95f592bfde288a955c1d521de1/test/versions.js#L244) doesn't work correctly...
*Also, setting proper git tags for each release would be great, so they don't have to be referred by their commit id (either for comments here or for targeting a specific version with npm).* 😃 
Thanks!
> Fix getVersion returning an undefined version

- README.md
- lib/index.js
- lib/utils.js
This is a follow up of #282
This will allow fine tune how the zip file is created. 
Example:
```js
nwjs: {
options: {
platforms: ['...'],
zip: true,
zipOptions: {
store: false,
level: 8,
}
}
```
> Allow zip options

- README.md
- lib/index.js
Since 32-bit OSX isn't supported by NW.js anymore (because OSX hasn't been released for 32-bit platforms since 2011), it's more friendly to new developers to not give them an error using the default `nwbuild` configuration.
This appears that it will conflict with #403, so if that gets merged I can rebase this.
> remove osx32 from the default list of platforms

- README.md
- lib/index.js
- package.json
Fixes https://github.com/nwjs-community/nw-builder/issues/196
Fixes https://github.com/nwjs-community/nw-builder/issues/315
Add `option.winVersionString` for accurate process name
The main goal was to fix the issue where the process showed up as `nwjs` in the Windows 10 Task Manager (now defaults to the `options.appName`). When trying to change `FileDescription` via [`rcedit`](https://www.npmjs.com/package/rcedit) as a post-process to the `nw-builder` build, I would always get a blank/default-shimmer NW.js page when starting up the app instead of the specified `main` file.
Allows you to edit the version string of the resultant Windows executable. These can be easily viewed in Properties -> Details,
```
winVersionString: {
'CompanyName': 'Some Company',
'FileDescription': 'Process Name', …
```
> Add option.winVersionString for accurate process name (always nwjs previously)

- lib/index.js
Thanks for the amazing nw-builder. Found a small problem when using it, if missing option.WinIco, option.winVersionString will not work. I think it should be independent of each other. This is the really first time I make a contribution, so please let me know if I did any thing wrong. Thanks again!
> Apply option.winVersionString even if there is no option.winIco

- .github/CHANGELOG.md
- lib/utils.cjs
- test/expected/osx-plist/1.plist
- test/expected/osx-plist/2.plist
Fixes: #505
- [Do not prefix](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring) `CFBundleShortVersionString` with `Version`
> fix(utils): do not append `Version` before `CFBundleShortVersionString`

- src/nwbuild.js
Fixes: #691
- Check for release info after downloading cache
> fix: failure if cache dir does not exist

- src/bld/osxCfg.js
- src/bld/package.js
This partially fixes macOS builds, but the entire renaming of helpers is commented out. With those changes enabled, NW.js won't launch. This PR at least gets builds to work, but the helpers are still named "nwjs". Will follow-up with Jared and/or the NW.js mailing list to determine what the proper procedure is.
- Replaces `nw.app` with `app.nw` for `osx` packaging step.
- Cleans up `osxCfg.js` to remove repetitive code and implement `node:path`.
- Implement `InfoPlist.strings` modification.
- Implement `product_string` property in `package.json` (currently disabled).
> fix: `osx` builds to allow nwjs launch

- package.json
- src/bld/winCfg.js
- src/nwbuild.js
- test/e2e/osx.cjs
Fixes: #714
- handle `rcedit` error on missing wine or if platform is not windows
> fix(win-bld): skip modify exe if platform is not windows or wine is not installed

- src/util/notify.js
Fixes: #766
- import the packageJson directly instead of reading it in runtime.
> fix: correct notify util

- src/bld/package.js
- src/bld/winCfg.js
- src/util/parse.js
> fix: prevent nuking `options.app`, use absolute path for `rcedit`

- src/nwbuild.js
When `glob` is set to `false`, the call to `getManifest()` was failing in Windows:
```
[ ERROR ] 2023-03-27T12:32:48.495Z ENOENT: no such file or directory, open 'C:\package.json'
```
This PR sets `files` to `options.srcDir` if `options.glob` is false. It works when globbing is disabled, but I don't know if it breaks anything when globbing is enabled.
> Fixes missing `files` when calling `getManifest()` with glob disabled

- src/bld/build.js
Fixes: #882
Continuation of #880
This makes the Nwjs files not have absolute paths in their symlinks. This may completely fix the osx64 code signing issue - maybe not.
> fix(fs): preserve relative symlinks of NW.js files

- changelog.md
- package-lock.json
- package.json
- src/get/getManifest.js
- src/get/getReleaseInfo.js
- src/util/validate.js
Fixes: #822
- Redownload `manifest.json` every time the `nwbuild` function is executed.
- If `manifest.json` already exists and we are unable to connect to the `nwjs.io` domain (network related issues), then use the existing manifest.
- If no `manifest.json` exists in the cache dir, then the validate function will catch this and throw an error - preventing the build.
> fix: change manifest cache impl

- .prettierignore
- changelog.md
- src/bld/build.js
- src/index.js
Fixes: #887
- Compress `outDir` to `zip`, `tar` and `tgz` formats.
> feat: compress to `zip`, `tar` and `tgz` formats

- changelog.md
- src/index.d.ts
- src/index.js
- src/log.js
- src/util/parse.js
- src/util/validate.js
- test/fixture/demo.js
- test/unit/parse.js
- test/unit/validate.js
Fixes: #844 
- Specify log level via `options.logLevel`.
- Add platform, arch, Node and NW.js info in debug log.
> feat: specify log level via `options.logLevel`

- changelog.md
- package-lock.json
- package.json
- src/cli.js
Fixes: #899
Previously `--glob false` was being parsed as `options.glob = "false"`. This also affected other arguments of types `object` and `boolean`. By adding argument types for the arguments, `--glob false` or `--glob=false` is parsed as `options.glob = false` and the other arguments are also parsed correctly.
> fix(yargs): specify arguments types

- changelog.md
- package-lock.json
- package.json
- src/bld/osxCfg.js
- test/fixture/demo.js
Fixes: #897
- Correctly set `NSHumanReadableCopyright` property.
- Fork repo
- Checkout `dev-897` branch
- `npm install` dependencies
- `npm run test:mod` to build demo app
- Go to `test/fixture/out/demo.app/Resources/en.lproj/InfoPlist.strings`
- Verify that `NSHumanReadableCopyright = "Copyright 2023 NW.js Utils. All Rights Reserved.";` exists in file
- Go to file explorer/Finder, right click and get app details `demo.app`
- Verify that the copyright is `Copyright 2023 NW.js Utils. All Rights Reserved.`
cc @rocketVibes
> fix(osx): set `NSHumanReadableCopyright` property

- src/bld/winCfg.js
Fixes: Windows icon not appearing. 
rcedit is used to modify the windows executable. We need to add the icon option for the icon to be set. Without this modification the executable will never get the icon. 
While testing this locally was seeing weird issues when building the application in the same output directory over and over. 
I moved to using a script to build in different output directories and the builds are entirely consistent now.
It seems that this change originated from this pr #894
> fix(win): enable icon

- src/get.js
Fixes: #na
There is an issue when downloading binaries that the builder doesn't wait for them to download and copies files immediately. 
This causes issues when the target applications files are moved before the file is downloaded. 
To fix this we simply return the promise from the request object. This will then make the function correctly wait. We were seeing intermittent failures on Jenkins when the cache was purged. 
Run without the return 
Run with the return
> fix(get): return promise to await correctly

- .gitignore
- src/get.js
Fixes: #916 
reinstate the `replaceFfmpeg` code that was removed during cleanup
> fix: move ffmpeg to correct folder after extract

- CODE_OF_CONDUCT.md
- changelog.md
- package.json
- src/get.js
Fixes: #923
This uses macOS built in `unzip` tool to unzip packages. On some macOS environments, the javascript `compressing` utility isn't restoring symlinks
> Fix missing symlinks in unzip

- src/index.d.ts
This PR changes `index.d.ts` so that:
- The documentation about the various options from index.js are also available through the type definitions;
- Platform-specific app options are also encoded in the types, with type conditionals so that they match the platform selected;
- Optional fields are marked as such, thus preventing errors when they are missing.
> fix(types): align type definitions with docs

- CHANGELOG.md
- package-lock.json
- package.json
- src/cli.js
Fixes: N/A
- Fix `yargs/helpers` import for cli usage.
> fix(cli): use asterisk import to import `yargs/helpers`

- .github/workflows/e2e.yml
- README.md
- package-lock.json
- package.json
- src/get/https.js
- src/get/https.test.js
- Factor out https logic.
- Separate `fs` from `https` wrapper implementation.
Notes: Unzipping MacOS binaries on MacOS is failing with `End of Central Directory Record not found` error which is unrelated to this change.
> chore(get): factor out https logic

- package-lock.json
- package.json
- src/get.js
- src/get/decompress.js
- src/util.js
- Use both absolute and relative paths for the cache directory.
-  Fixes the issue on MacOS related to the existence of a cache folder that is not present in the same current directory.
- Correctly unzips files in MacOs.
Notes: Resolves issued caused by cache is in a directory other than the current path.
Closes: #1017
> feat(get): set `cacheDir` on another volume

- README.md
- src/run.js
- Mark run mode as deprecated
Notes: nw-builder needs to focus on building and packaging apps. Instead of maintaining a run mode, port this behaviour to nwjs/npm-installer and improve interop between the tools.
> chore(run): mark run mode as deprecated

- .github/workflows/e2e.yml
- README.md
- package-lock.json
- package.json
- src/get/decompress.js
- src/get/index.js
- test/fixture/demo.js
- test/specs/get.test.js
* Do not mix Promise and Callback APIs.
* Remove `createSymlinks` function workaround
Refs: https://github.com/overlookmotel/yauzl-promise/issues/39#issuecomment-1934849379
> chore(get): refactor unzip symlink implementation

- src/get/decompress.js
* Current implementation: write entry as file, check if entry is symlink, remove file and create symlink
* Improved implementation: check if entry is symlink, stream entry to buffer, extract link target and create symlink. Otherwise, stream entry to file.
Refs: #1030
> chore(get): simplify symlink logic

- src/get/index.js
* Windows FFmpeg copy was breaking because the destination path was never set
> fix(get): copy ffmpeg to correct location on windows

- .github/workflows/e2e.yml
- LICENSE
- package-lock.json
- package.json
- src/bld.js
- src/bld/osx.js
- src/index.js
- tests/fixtures/app/package.json
- tests/fixtures/demo.js
- tests/specs/osx.test.js
* Updates the Plist properties and renames the relevant executables.
Fixes: https://github.com/nwjs/nw.js/issues/7253
Refs: https://nwjs.readthedocs.io/en/latest/For%20Users/Package%20and%20Distribute/
> feat(bld): rename MacOS Helper apps

- README.md
- src/bld.js
- src/bld/osx.js
- src/index.d.ts
- src/util.js
- tests/specs/osx.test.js
* Declare why an app needs to access the local network
Fixes: #1235
Refs: https://developer.apple.com/forums/thread/663858
Refs: https://developer.apple.com/documentation/bundleresources/information_property_list/nslocalnetworkusagedescription
> feat(bld): add NSLocalNetworkUsageDescription option for MacOS

- eslint.config.js
- src/util.js
* This mitigates potential path traversal.
Fixes: #1258
> fix(util): strip special and control characters from app.name

- README.md
> chore(docs): clarify priority for defined options

- package-lock.json
- package.json
- src/cli.js
- src/util.js
Fixes: #1277
Refs: https://github.com/nwutils/nw-angular-example/actions/runs/11138590579/job/30953806800?pr=162
> fix(cli): handle boolean type options correctly

- README.md
- package.json
- src/bld.js
- src/index.js
- src/util.js
- tests/fixtures/demo.js
* Replace special and control characters iff options.app.name is a string
Fixes: #1286
> fix(bld): set product_string property in manifest to rename MacOS Helper apps

- README.md
- src/run.js
- tests/fixtures/app/package.json
- tests/specs/bld.test.js
- tests/specs/osx.test.js
- tests/specs/run.test.js
* This allows us to kill the process via code which is useful during testing.
> feat(run): return NW.js process reference

- README.md
- src/cli.js
- src/get/index.js
- src/get/verify.js
- src/index.js
- src/util.js
* Fix a manifest not found error
* Correctly parse options.* values
> feat(get): add options.shaSum to enable/disable shasum checks

- .github/workflows/e2e.yml
- SECURITY.md
- src/bld.js
> fix(bld): await archiver.finalize
