nwutils/nw-builder

- README.md
- bin/nwbuild
- example/Gulpfile.js
- example/nwapp/index.html
- example/nwapp/package.json
- example/package.json
- lib/index.js
- lib/utils.js
- package.json
- test/expected/osx-plist/1.plist
- test/expected/osx-plist/2.plist
- test/fixtures/osx-plist/Info.plist
> Renaming the module

- bin/nwbuild
- lib/detectCurrentPlatform.js
- lib/index.js
- lib/utils.js
- lib/versions.js
It doesn't have any impact on the functionality, but for cosmetic reasons :smile:
> Fixed some semicolons

- README.md
- bin/nwbuild
Added new option to specify the cache directory.
> cacheDir option added

- bin/nwbuild
> make commandline to accept --flavor  argument

- lib/index.js
- lib/versions.js
- test/versions.js
Secure downloads should be the default...
https://github.com/nwjs/nw.js/issues/3228#issuecomment-237153818
> Download NW.js archives via https

- lib/downloader.js
> osx 0.20.3 normal only has 2 files at root folder

- README.md
And fix some formatting via invisible end-of-line whitespace
> Improve docs around run

- README.md
The wiki page doesn't seem maintained any more and is out of date.
> Update nw.js releases link

- README.md
Fixes: #436 
- Update NW.js version in README
- Fix NW.js releases hyperlink
- Fix Changelog link
> fix(docs): update versions, fix broken links

- lib/index.js
- package.json
- pnpm-lock.yaml
Fixes: #558
- Updated dependencies which had no breaking changes and did not cause tests to fail
- `request`, `nock` and `extract-zip` will be delt with in separate PRs
> chore(deps): update deps

- .github/CHANGELOG.md
- package-lock.json
- package.json
Fixes: #641 
- Fixed windows and mac build
> fix: mac and windows build

- src/bld/compress.js
Fixes: #692 
- Resolve promise in close event
> fix(compression): resolve promise in close event

- package.json
- src/bld/compress.js
- src/nwbuild.cjs
- test/bld.cjs
Fixes: #696 
- Add back CJS support
> fix: cjs support

- src/nwbuild.js
> fix: correct nwbuild validation logic

- changelog.md
- package-lock.json
- package.json
- src/cli.js
- src/util/parse.js
- test/fixture/demo.js
> fix(glob): do not resolve `options.srcDir` when parsing `options` object 

- .github/workflows/doc.yml
- .github/workflows/e2e.yml
- .github/workflows/npm.yml
- cfg/fswatch.config.js
- changelog.md
- src/bld/winCfg.js
- src/get.js
- src/index.js
- test/e2e/mode.js
Refs: https://github.com/nwutils/nw-builder/pull/906#pullrequestreview-1559809630
Chromedriver fails when globbing is enabled. Disabled globbing for now.
> fix(test): disable glob in chromedriver tests

- .gitignore
- changelog.md
- package.json
- src/get.js
- src/util/ffmpeg.js
> Copy ffmpeg to correct path after extract

- lib/index.cjs
- package-lock.json
- src/get.js
- test/demo.cjs
> fix(build): rename executable

- .github/workflows/doc.yml
- .github/workflows/e2e.yml
- .github/workflows/npm.yml
- package.json
Fixes: N/A
By adding more Node versions, we will be able to ensure compatibility across different Node major versions.
> ci: add Node 16, 18 and 20

- .github/workflows/e2e.yml
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/get.js
- test/e2e/index.js
- test/fixture/demo.js
> feat(get): align cache impl with `nwjs/npm-installer`

- .github/workflows/e2e.yml
- CHANGELOG.md
- package-lock.json
- package.json
- src/get.js
- test/e2e/addon.js
- test/e2e/index.js
- test/e2e/mode.js
- test/fixture/demo.js
> fix(compressing): use `yauzl-promise` if platform and build is MacOS

- src/bld.js
- src/index.js
- src/util.js
- src/util/parse.js
- test/fixture/demo.js
Fixes: N/A
- See https://github.com/nwutils/nw-builder/issues/970
> docs: disable `options.nativeAddon`

- README.md
- src/get/nw.js
- src/get/nw.test.js
- Factor out NW.js download logic
> chore(get): factor out nw download logic

- README.md
- src/get/ffmpeg.js
- src/get/ffmpeg.test.js
- Factor out FFmpeg download logic
> chore(get): factor out ffmpeg download logic

- README.md
- src/get/node.js
- src/get/node.test.js
- Factor out Node headers download logic.
> chore(get): factor out node headers download logic

- README.md
- src/get/index.js
Depends on: https://github.com/nwjs/npm-installer/pull/135
> chore(get): deprecate get mode

- README.md
- package.json
- src/cli.js
* display choices for various options
* update incorrect types
Note: this prevents people/AI from using v3 options in v4 cli
> fix(cli): disallow unknown options

- src/bld.js
> fix(bld): maintain cwd when using managedManifest or nativeAddon

- src/index.d.ts
Fixes: #1248
Refs: https://github.com/nwutils/nw-builder/blob/main/README.md#build-mode
> fix(types): add managedManifest parameter in options

- .gitignore
- README.md
- src/bld.js
- src/index.d.ts
- src/index.js
- src/util.js
- tests/specs/bld.test.js
- tests/specs/osx.test.js
- tests/specs/run.test.js
> fix: update default NW.js version url

- package.json
- src/cli.js
> fix(cli): parse --app.* options

- src/cli.js
> fix(cli): parse argument as srcDir option
